### ISSUE TITLE
Question: How to "install" an app?  

### ISSUE THREAD

**Issue by Moltkex** [AppImageCrafters/appimage-manager#7]
Hi, 

I just installed in Ubuntu and already tried to "install/download" an app, however, I keep getting this 
`appimage-cli-tool: error: invalid target format`

What is or are the valid formats? Because 

```
app install --help          
Usage: appimage-cli-tool install <target>

Install an application.

Arguments:
<target> Installation target.

Flags:
-h, --help Show context-sensitive help.
--debug Enable debug mode.
```

Doesn't really help that much. Thanks for any help in advance.

**Comment by 0cwa** [comment]
Same issue with `app install <name>`
And with a .appimage file:
```
$ sudo app install FontBase-2.16.9.AppImage 
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x5f4822]

goroutine 1 [running]:
github.com/alecthomas/kong.catch(0xc0000dbf50)
        /go/pkg/mod/github.com/alecthomas/kong@v0.2.11/kong.go:366 +0xb3
panic(0x999b60, 0xde4050)
        /usr/local/go/src/runtime/panic.go:969 +0x1b9
github.com/rainycape/dl.(*DL).Sym.func2(0x0, 0x28cb6c0, 0x28cb6c0)
        /go/pkg/mod/github.com/rainycape/dl@v0.0.0-20151222075243-1b01514224a1/dl.go:86 +0x22
github.com/rainycape/dl.(*DL).Sym(0x0, 0xa6bd07, 0x20, 0x9548e0, 0xc0001cc728, 0x0, 0x0)
        /go/pkg/mod/github.com/rainycape/dl@v0.0.0-20151222075243-1b01514224a1/dl.go:86 +0xc9
appimage-cli-tool/internal/utils.NewLibAppImageBindings(0xc0001cb2b0, 0xc000024b80, 0x18, 0xc0001cb2e8)
        /builds/azubieta/appimage-cli-tool/internal/utils/libappimage.go:46 +0x91
appimage-cli-tool/cmd/commands/install.(*InstallCmd).createDesktopIntegration(0xecf418, 0xc000024b80, 0x18)
        /builds/azubieta/appimage-cli-tool/cmd/commands/install/install.go:88 +0x34
appimage-cli-tool/cmd/commands/install.(*InstallCmd).Run(0xecf418, 0xc0000273d8, 0x0, 0x0)
        /builds/azubieta/appimage-cli-tool/cmd/commands/install/install.go:18 +0x4d5
reflect.Value.call(0x9b4860, 0xecf418, 0x213, 0xa566cc, 0x4, 0xc0001cc6c0, 0x1, 0x1, 0x1, 0x0, ...)
        /usr/local/go/src/reflect/value.go:476 +0x8c7
reflect.Value.Call(0x9b4860, 0xecf418, 0x213, 0xc0001cc6c0, 0x1, 0x1, 0x0, 0x1, 0xc0000dbc88)
        /usr/local/go/src/reflect/value.go:337 +0xb9
github.com/alecthomas/kong.callMethod(0xa5603b, 0x3, 0x9b9c40, 0xecf418, 0x199, 0x9b4860, 0xecf418, 0x213, 0xc0001c7a70, 0x4, ...)
        /go/pkg/mod/github.com/alecthomas/kong@v0.2.11/callbacks.go:71 +0x4b1
github.com/alecthomas/kong.(*Context).RunNode(0xc0000f6600, 0xc000095ba0, 0xc0000dbf68, 0x1, 0x1, 0x4106b8, 0x1)
        /go/pkg/mod/github.com/alecthomas/kong@v0.2.11/context.go:610 +0x571
github.com/alecthomas/kong.(*Context).Run(0xc0000f6600, 0xc0000dbf68, 0x1, 0x1, 0x0, 0x0)
        /go/pkg/mod/github.com/alecthomas/kong@v0.2.11/context.go:627 +0x99
main.main()
        /builds/azubieta/appimage-cli-tool/cmd/main.go:23 +0xb9
```

**Comment by BuriedStPatrick** [comment]
Adding my confusion to the list here. This is the only format that doesn't give me an invalid target format:

```bash
# Example, installing App Outlet
# I got the target from 'app search app-outlet'
app install appimagehub:1355468
```
However, I instead get this response:

```.
appimage-cli-tool: error: no AppImage found in releases
```

Which I can't really make sense of. There is a `App.Outlet-2.1.0.AppImage` file in this particular repository if I look in AppImageHub:

https://www.appimagehub.com/p/1355468

**Comment by i18nde** [comment]
Same here, if I ask:
`app search balena`
`...`
`appimagehub:1222201  BalenaEtcher - Appimage Utilities           AJSlye`

Now I want to install Balena Etcher, I got this:

`app install appimagehub:1222201 `
`appimage-cli-tool: error: no AppImage found in releases `

Only if I give the full path e.g for Lagrange

`app install https://github.com/skyjake/lagrange/releases/download/v1.13.7/Lagrange-1.13.7-x86_64.AppImage`

I got even to  choose between

`Use the arrow keys to navigate: ↓ ↑ → ← `
`Select binary to download`
`  ✅ Lagrange-1.13.7-armhf.AppImage`
`     Lagrange-1.13.7-x86_64.AppImage`

and it works. Mayby the database at appimagehub.com has some defects? Or does it only work at github?

It's really a pity, because I think it's a neat and nice tool, if it works. ;-)
